on: [pull_request]

jobs:
  hello_world_job:
    permissions: write-all
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - name: Reviewing Code 
        id: hello
        # uses: akshay-rao-h2/test-github-actions@v1.28
        uses: rahul-mahato11/test-prgenie-gpt@1.2
        with:
          pr-link: ${{ github.event.number }}
          token: ${{ github.token }}
          AITOKEN: 'bd080fbfa94c82cc70eb5bab7146b5a6850a5c6966541a00aaa1a33aeb944d8b61d5a43f256982bc3459ab09c4fedf52c49e1a406f77e8da25e7a5cfffdf91810148819c68cbe5a7e3f5eb7f3cfce2aa7c5423ab9d832add771769902bbd8b2e1882aa4c89bb900b88bac47d63f6476e382e8b7418642c0c897c91dc6d34b2778c839700840f9c3b0b8c4db252b2df550ca0d2'
          repo: ${{ github.repository }}
          commit-id: ${{ github.sha }}
      # Use the output from the `hello` step
      - name: Get the output time
        run: echo "The time was ${{ steps.hello.outputs.time }}"